name: Daily Build and Test

on:
  schedule:
    - cron: "0 8 * * *"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Send POST request
      run: |
        curl -X POST -H "Content-Type: application/json" -H "mallid: 220598746827" -d '{}' -b "SUB_PASS_ID=eyJ0IjoiWnBnZEJqbFBtMytTMzZjVTVYK0hyOW5tZ1N4TndRR3BtalQ5T3htK2hFa0t6NTZRc3I2TkVjL0N1S05aV3ArSCIsInYiOjEsInMiOjEwMDAwLCJ1IjozNjU4ODU3NDAwMTd9" https://seller.kuajingmaihuo.com/api/merchant/payment/account/amount/info > response.json
        jq -r '.' response.json

    - name: Send another POST request with the availableBalance value from the first response
      run: |
        cat response.json | jq -r '.result.availableBalance' > balance.txt
        echo '{ "msgtype": "text","text": {"content": "跨境主店当前可用余额'$(cat balance.txt)'"}}' > data.json
        curl -X POST -H "Content-Type: application/json" -d "@data.json" https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=576f92ae-b64c-4069-bcc6-855809e867e8
